apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-11-02T15:12:13Z"
  generation: 2
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 9443a327-c82e-477f-a89c-daef58f23fe9
  resourceVersion: "51738"
  uid: 7d00c54d-da7e-4bda-af60-1eb1e4242012
spec:
  additionalTrustedCA:
    name: registry-config
status:
  internalRegistryHostname: image-registry.openshift-image-registry.svc:5000
