apiVersion: config.openshift.io/v1
kind: Image
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-06-18T10:37:40Z"
  generation: 1
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 6105fe6f-04cb-4e8c-898e-5b476a9b3427
  resourceVersion: "1528"
  uid: 4fa46b98-a450-48ab-8035-6a6cf18125b5
spec: {}
